### ISSUE TITLE
Invalid patch file

### ISSUE THREAD

**Issue by whatisor** [haiyangwu/mediasoup-client-android#1]
I think path file is out of date. I got this issue when try to apply path:
error: patch failed: build/config/android/BUILD.gn:105
error: build/config/android/BUILD.gn: patch does not apply

We should be able to use dynamic library, right?

**Comment by haiyangwu** [comment]
The path file is just for **webrtc#m74**. It worked fine for me. Please check your webrtc version.

>We should be able to use dynamic library, right?

Use static library is better for we can debug with webrtc in some cases.
