### ISSUE TITLE
Whether to add a stop interface?

### ISSUE THREAD

**Issue by jackzhangkun** [haiyangwu/mediasoup-client-android#18]
Whether to add stop local video, stop  local audio, stop remote video,stop remote audio interface?

**Comment by haiyangwu** [comment]
Already contained these functions:
* stop local video/audio, Producer#pause
* stop remote video/audio, Consumer#pause

[Demo](https://github.com/haiyangwu/mediasoup-demo-android) shows theses basic operations.
