### ISSUE TITLE
audio volume is pretty low when speaker is on

### ISSUE THREAD

**Issue by lusfold** [haiyangwu/mediasoup-client-android#21]
Volume is normal when the speaker off, but if turn on the speaker, the mic volume is low, and it is hard to hear. Is there any way to set the volume of the microphone when the speaker is on?

**Comment by lusfold** [comment]
Got a simple solution: turn the speaker on before joining the room

**Comment by iQuick** [comment]
I also have this problem, but after setting it according to your method, there will be a lot of noise. Do you have this situation?
