### ISSUE TITLE
Duplicate a=mid value '2'

### ISSUE THREAD

**Issue by KurdAppDev** [haiyangwu/mediasoup-client-android#23]
above 3.0.4-beta-2 it has this error with 3 devices and more

`[WARN] PeerConnection::OnFailure() | webtc::SetSessionDescriptionObserver failure [INVALID_PARAMETER:Failed to set remote offer sdp: Duplicate a=mid value '2'.]`

`E/mediasoupclient-jni: [ERROR] transport_jni::JNI_RecvTransport_Consume() | Failed to set remote offer sdp: Duplicate a=mid value '2'.`

**Comment by KurdAppDev** [comment]
There is a way to fix this or we will have to wait for a new update?

**Comment by zeeshanrasool91** [comment]
Same issue i also raised if anyone can help on that it will be highly appreciated

**Comment by YangZhouYz** [comment]
@作者 请问，这个问题有什么解决办法？我卡在这个问题好久了。

**Comment by haiyangwu** [comment]
Already found the root cause，I'll fix it but still waiting for @jmillan's advice. A quick workaround was to remove code related to Consumer for RTP probation as mentioned in https://github.com/versatica/libmediasoupclient/issues/83.

**Comment by jmillan** [comment]
Where you able to confirm the fix @haiyangwu?

**Comment by haiyangwu** [comment]
@jmillan Already tested in my local environment and your fix commit worked. However, due to network problem (maybe limited by GFW), I can't upload the new version `org.mediasoup.droid:mediasoup-client:3.0.8-beta-2` to `https://bintray.com/` 😞

**Comment by jmillan** [comment]
super :-)
