### ISSUE TITLE
Video consumer only support Software Decoder

### ISSUE THREAD

**Issue by whatisor** [haiyangwu/mediasoup-client-android#27]
I add log to trace flow of code from mediasoupclient to webrtc.
for video consuming, it uses libvpx which is only software based.
`2020-05-31 18:19:35.083 15115-15247/? I/libvpx_vp8_decoder.cc: (line 159): LibvpxVp8Decoder::Decode`

Can we switch to hardware decoder of android such as OMX?

**Comment by haiyangwu** [comment]
@whatisor pls check the source code of `webrtc`, If you want to support other codecs, change the source file and replace the prebuild library in the repo.

 > https://chromium.googlesource.com/external/webrtc/+/branch-heads/m79/sdk/android/src/java/org/webrtc/MediaCodecVideoDecoderFactory.java
