### ISSUE TITLE
WebSocket Disconnected

### ISSUE THREAD

**Issue by zeeshanrasool91** [haiyangwu/mediasoup-client-android#34]
Hi , we deployed the latest code on our own server, when i am trying to connect to server it is showing Websocket disconnected

**Comment by haiyangwu** [comment]
Sorry, it's out the scope of this repo, pls debug yourself.

**Comment by zeeshanrasool91** [comment]
I am trying seems like the request time out... can you guide me is there any issues from server side implementation. we deployed it on AWS server. help will be highly appreciated.
