### ISSUE TITLE
使用构建webrtc的构建命令无法得到.a文件，大家知道如何解决么？

### ISSUE THREAD

**Issue by sunjihai** [haiyangwu/mediasoup-client-android#46]
# webrtc-android-build
Precompiled binaries for webrtc android native

* Build m79 with command like below

```
./tools_webrtc/android/build_aar.py --extra-gn-args 'is_debug=false is_component_build=false is_clang=true rtc_include_tests=false rtc_use_h264=true rtc_enable_protobuf=false use_rtti=true use_custom_libcxx=false' --build-dir ./out/release-build/
```
使用改命令后，无法找到"libwebrtc.a"文件。

**Comment by big-brain** [comment]
> # webrtc-android-build
> Precompiled binaries for webrtc android native
> 
> * Build m79 with command like below
> 
> ```
> ./tools_webrtc/android/build_aar.py --extra-gn-args 'is_debug=false is_component_build=false is_clang=true rtc_include_tests=false rtc_use_h264=true rtc_enable_protobuf=false use_rtti=true use_custom_libcxx=false' --build-dir ./out/release-build/
> ```
> 
> 使用改命令后，无法找到"libwebrtc.a"文件。

libwebrtc.a不是用这种方式生成的
-- target_cpu=x86,x64,arm,arm64
gn gen out/release/x64 --args='target_os="android" target_cpu="x64" is_debug=false'
ninja -C out/release/x64

**Comment by sunjihai** [comment]
嗯嗯，用这种方式生成了libwebrtc.a文件，但是替换后编译不过。

**Comment by itcayman** [comment]
> 嗯嗯，用这种方式生成了libwebrtc.a文件，但是替换后编译不过。

请问解决了么，我替换后也是编译失败

**Comment by big-brain** [comment]
> 嗯嗯，用这种方式生成了libwebrtc.a文件，但是替换后编译不过。
gn gen out/release/x64 --args='target_os="android" target_cpu="arm" is_debug=false is_component_build=false is_clang=true rtc_include_tests=false rtc_use_h264=true rtc_enable_protobuf=false use_rtti=true use_custom_libcxx=false'

按上述方式生产arm的静态库，相关的头文件也需要替换，linux上面把原来的src删除了，把webrtc_android的src通过软连接连接过去，再编译

**Comment by QtyearLin** [comment]
> > 嗯嗯，用这种方式生成了libwebrtc.a文件，但是替换后编译不过。
> > gn gen out/release/x64 --args='target_os="android" target_cpu="arm" is_debug=false is_component_build=false is_clang=true rtc_include_tests=false rtc_use_h264=true rtc_enable_protobuf=false use_rtti=true use_custom_libcxx=false'
> 
> 按上述方式生产arm的静态库，相关的头文件也需要替换，linux上面把原来的src删除了，把webrtc_android的src通过软连接连接过去，再编译

你的意思是把webrtc源码替换为client deps下面的src么 ？

**Comment by haiyangwu** [comment]
@big-brain Thx for sharing. close issuse
