### ISSUE TITLE
Get rtp url of remote client to stream by external streamer

### ISSUE THREAD

**Issue by whatisor** [haiyangwu/mediasoup-client-android#7]
Hi,
Is there any way to get rtp url of peer client to play stream by external streamer such as vlc, ffmpeg?
Thank you.

**Comment by haiyangwu** [comment]
Implement another org.webrtc.VideoCapturer may solve your problem, but it's out of the scope of current project.

**Comment by whatisor** [comment]
@haiyangwu , thank for response.
That is bad new for me.
Do you think I can use this solution?
createPlainRtpTransport
https://groups.google.com/forum/#!topic/mediasoup/3xmlVtUBx9U
https://github.com/versatica/mediasoup/tree/d7ff7e69158c246e18707424c2cdb3b0b1cc5b4f
https://mediasoup.org/documentation/v3/communication-between-client-and-server/
