### ISSUE TITLE
device.load unsupport video 

### ISSUE THREAD

**Issue by PhilanthropistBright** [haiyangwu/mediasoup-client-android#9]
Please! I find do Device Class load(routerRtpCapabilities) and getRtpCapabilities() just return audio sdpmessage

**Comment by haiyangwu** [comment]
Pls upload more info, eg. the parameter of `Device#load`.

**Comment by whatisor** [comment]
Same here:
https://github.com/haiyangwu/mediasoup-demo-android/issues/4

**Comment by haiyangwu** [comment]
@whatisor pls upload running log from logcat. BTW It's open-source, may you pls debug with your device, figure out the root cause and create a PR ? 👏

**Comment by whatisor** [comment]
@haiyangwu 1,2 month ago, it works well.
Then suddenly, it stops working.
Have you changed https://v3demo.mediasoup.org/ setting?
I tried with https://github.com/versatica/mediasoup-demo to setup local server, but same issue.

I wonder if https://v3demo.mediasoup.org source is totally same with https://github.com/versatica/mediasoup-demo?

**Comment by ethand91** [comment]
@whatisor 
Could you share what device you are using?
Also would be interested in the log and the sdp offer generated by the device.

**Comment by whatisor** [comment]
@ethand91 I shared log here:
haiyangwu/mediasoup-demo-android#4

I am using Android Emulator. It worked with VP8 last time.

**Comment by whatisor** [comment]
Real-time update, now I am debugging.
Matching codec steps is crazy, it compares local vp8 with all other remote but not vp8 remote

[DEBUG] ortc::matchCodecs() | Mime diff video/vp8-audio/opus
[DEBUG] ortc::matchCodecs() | Mime diff video/vp8-video/vp9
[DEBUG] ortc::matchCodecs() | Mime diff video/vp8-video/h264
[DEBUG] ortc::matchCodecs() | Mime diff video/vp8-video/h264
[DEBUG] ortc::matchCodecs() | Mime diff video/vp8-audio/opus
[DEBUG] ortc::matchCodecs() | Mime diff video/vp8-video/vp9
[DEBUG] ortc::matchCodecs() | Mime diff video/vp8-video/h264
[DEBUG] ortc::matchCodecs() | Mime diff video/vp8-video/h264

**Comment by haiyangwu** [comment]
@whatisor I just verified on my phone, it's broken now. Maybe some update of https://v3demo.mediasoup.org/ leads to the bug. I'll fix it, but sorry, time not guaranteed 🤫

**Comment by whatisor** [comment]
@haiyangwu , just please try to remove channels info from video codecs.

**Comment by PhilanthropistBright** [comment]
> @haiyangwu，请尝试从视频编解码器中删除频道信息。

you are right   I remove video channel is OK  Thanks'

**Comment by haiyangwu** [comment]
@whatisor Thx, following your advice, a quick fix already committed and it works.
